### PR TITLE
Update -Wno options

### PR DESCRIPTION
**Pull request by bje-**
Many of the G++ `-Wno-*` options are no longer required for the current code base, so trim them.

Note this branch is taken off `wx-deprecated` which includes my previous patch -- so that the build will not fail. This patch should be considered after PR #17.

### CODE REVIEW

**Comment by bje-** [comment]
Sorry, not sure how the change removing the `register` keyword ended up on this branch. I can split them apart if you prefer?

**Comment by dguittet** [comment]
No, I'm sorry for not being clear. I intended to leave this open to see if there were any other reviews on it, but meant that it looked fine to me. Could you un-revert?

**Comment by bje-** [comment]
I created a separate PR #19

**Comment by bje-** [comment]
This is a trivial change now. It just removes a handful of G++ `-Wno` options that are no longer required.

**Comment by dguittet** [comment]
Yup, thanks for splitting those up! It looks good to me. Just waiting for the Travis check

**Comment by dguittet** [comment]
Actually, there's an issue on osx due to a deprecated function for osx 10.12 onward.

```
[ 50%] Building C object lk/CMakeFiles/lk.dir/src/sqlite3.c.o
/Users/dguittet/SAM-Dev/lk/src/sqlite3.c:20751:17: error: 'OSAtomicCompareAndSwapPtrBarrier' is deprecated: first deprecated in macOS 10.12 - Use atomic_compare_exchange_strong() from <stdatomic.h> instead [-Werror,-Wdeprecated-declarations]
      success = OSAtomicCompareAndSwapPtrBarrier(NULL, newzone, 
                ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/libkern/OSAtomicDeprecated.h:547:6: note: 'OSAtomicCompareAndSwapPtrBarrier' has been explicitly marked deprecated here
bool    OSAtomicCompareAndSwapPtrBarrier( void *__oldValue, void *__newValue, void * volatile *__theValue );
```

Since, we do support osx 10.9, could you check that atomic_compare_exchange_strong is available for 10.9?

**Comment by bje-** [comment]
`atomic_compare_exchange_strong` is in C11 and C++11. See: https://en.cppreference.com/w/c/atomic/atomic_compare_exchange

**Comment by dguittet** [comment]
Looks like this is from sqlite3 src code and only affects single core devices. So rather than just replace the function, it looks like sqlite has actually fixed the code to fix the warning: https://github.com/mattn/go-sqlite3/issues/332

I copied over this section from the current sqlite3 src code: https://www.sqlite.org/src/info/c12a42539b1ba105

**Comment by bje-** [comment]
Thanks. I'm not too fussed how it gets fixed. :smile:

**Comment by dguittet** [comment]
Hah, I am just because if it breaks in the future, I'd like to know what happened!

**Pull request merged**
