### PR TITLE
Ci Runners for Windows & Mac

### PR DESCRIPTION
**Pull request by dguittet**
CI for Windows and Mac Intel & Arm

Add build for lk_sandbox

wxWidgets binaries are installed from wxWidgets repo for Windows and brew for Mac. This is much faster than building it from source.

### CODE REVIEW

**Review by sjanzou — APPROVED** [review]
Awesome job pulling the binaries! I think we will need to make sure everyone is using the same versions of wxWidgets when developing.

**Comment by dguittet** [comment]
For sure the developers should be using the version from the wiki. But if we can build and test SAM with different versions of wxWidgets in a fraction of the time, it seems worthwhile to mix versions for CI.

**Comment by dguittet** [comment]
I can fix the install from brew to 3.2.3 to reduce that version confusion.

**Comment by dguittet** [comment]
However, it seems like downloading the binaries directly for wex and SAM isn't going to work. It looks SAM is using a static build of wx but the binary downloads will be dll builds of wx. Not sure how easy it is to flip that on and off, or whether it is worth it in order to reduce the amount of time it takes to run the SAM test on CI. If we could use the dll releases of wx, the SAM tests would be quite a bit faster given how long the wxWidgets build takes.

**Review by brtietz — APPROVED** [review]
Looks great, thanks for adding tests and updating versions!

**Pull request merged**
